## 1. Numpy - ndarray

### 1.1 ndarray 생성 
np.array()

In [2]:
import numpy as np

In [2]:
list1 = [1,2,3]

print(list1)
print(type(list1))

[1, 2, 3]
<class 'list'>


In [3]:
array1 = np.array(list1)

print(array1)
print(type(array1))

[1 2 3]
<class 'numpy.ndarray'>


### 1.2 ndarray의 형태(shape)과 차원 

In [4]:
array1 = np.array([1,2,3])

print(type(array1))
print(array1.shape)

<class 'numpy.ndarray'>
(3,)


In [5]:
array2 = np.array([[1,2,3],
                   [2,3,4]])

print(type(array2))
print(array2.shape)

<class 'numpy.ndarray'>
(2, 3)


In [6]:
array3 = np.array([[1,2,3]])

print(type(array3))
print(array3.shape)

<class 'numpy.ndarray'>
(1, 3)


In [42]:
print(array1.ndim)    # array의 차원
print(array2.ndim)
print(array3.ndim)

1
2
2


### 1.3 ndarray 데이터 값 타입

In [8]:
list1 = [1,2,3]
print(type(list1))

array1 = np.array(list1)
print(type(array1))

print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [9]:
list2 = [1,2, 'test']
array2 = np.array(list2)

print(array2, array2.dtype)    # u11은 문자열 타입의 한 종류

['1' '2' 'test'] <U11


In [10]:
list3 = [1,2,3.0]
array3 = np.array(list3)

print(array3, array3.dtype)

[1. 2. 3.] float64


### 1.4 astype()을 통한 타입 변환

In [11]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')

print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [12]:
array_int1 = array_float.astype('int32')

print(array_int1, array_int1.dtype)

[1 2 3] int32


In [13]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')

print(array_int2, array_int2.dtype)

[1 2 3] int32


### 1.5 ndarray에서 axis 기반의 연산함수 수행 

In [14]:
array2 = np.array([[1,2,3],
                  [2,3,4]])

print(array2.sum())
print(array2.sum(axis=0))
print(array2.sum(axis=1))

15
[3 5 7]
[6 9]


### 1.6 ndarray를 편리하게 생성하기 - arange, zeros, ones

In [15]:
sequence_array = np.arange(10)

print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [17]:
zero_array = np.zeros((3,2), dtype = 'int32')

print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [18]:
one_array = np.ones((3,2))

print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


### 1.7 ndarray의 shape를 변경하는 reshape()

In [19]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [20]:
array2 = array1.reshape(2,5)
print(array2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [21]:
array3 = array1.reshape(5,2)
print(array3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [37]:
array1.reshape(4,3)    # 변환할 수 없는 shape구조를 입력하면 오류 발생

ValueError: cannot reshape array of size 10 into shape (4,3)

>reshape()에 -1 인자값을 부여하여 특정 차원으로 고정된 <br>가변적인 ndarray 형태 변환

In [22]:
array1 = np.arange(10)
print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [23]:
# 칼럼 axis 크기는 5에 고정하고 로우 axis 크기를 이에 맞춰 자동으로 변환

array2 = array1.reshape(-1,5)
print(array2.shape)
print(array2)

(2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [24]:
# 로우 axis 크기는 5로 고정하고 칼럼 axis 크기를 이에 맞춰 자동으로 변환

array3 = array1.reshape(5,-1)
print(array3.shape)
print(array3)

(5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


>reshape()는 (-1, 1)이나 (-1,)와 같은 형태로 주로 사용<Br>
    1차원 ndarray를 2차원으로 변환하거나,<br>
    2차원 ndarray를 1차원으로 변환 시 사용


In [34]:
array1 = np.arange(5)

print(array1)

[0 1 2 3 4]


In [36]:
# 1차원 ndarray를 2차원으로 변환하되, 컬럼axis 크기는 반드시 1이어야 함

array2d_1 = array1.reshape(-1, 1)

print(array2d_1)
print(array2d_1.shape)

[[0]
 [1]
 [2]
 [3]
 [4]]
(5, 1)


In [38]:
# 2차원 ndarray를 1차원으로 변환

array1d = array2d_1.reshape(-1,)

print(array1d)
print(array1d.shape)

[0 1 2 3 4]
(5,)


In [44]:
# -1을 적용하여도 변환이 불가능한 형태로의 변환을 요구할 경우 오류 발생

array1 = np.arange(10)
array4 = array1.reshape(-1,4)

ValueError: cannot reshape array of size 10 into shape (4)

In [45]:
# 반드시 -1 값은 1개의 인자만 입력해야 함
array1.reshape(-1,-1)

ValueError: can only specify one unknown dimension

## 2. ndarray의 데이터 세트 선택하기 - 인덱싱 (Indexing)

### 2.1 특정 위치의 단일값 추출

In [46]:
array1 = np.arange(start=1, stop=10)
print(array1)

[1 2 3 4 5 6 7 8 9]


In [48]:
value = array1[2]    # 인덱스는 0부터 시작

print(value)
print(type(value))

3
<class 'numpy.int32'>


In [52]:
print(array1[-1])    # 맨 뒤의 값
print(array1[-2])    # 맨 뒤에서 두번째 값

9
8


In [54]:
array1[0] = 9
array1[8] = 0

print(array1)

[9 2 3 4 5 6 7 8 0]


In [56]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
print(array2d[0,0])    # row=0, col=0 인덱스
print(array2d[0,1])    # row=0, col=1 인덱스
print(array2d[1,0])    # row=1, col=0 인덱스
print(array2d[2,2])    # row=2, col=2 인덱스

1
2
4
9


### 2.2 슬라이싱 (slicing)

In [61]:
array1 = np.arange(start=1, stop=10)

print(array1)

[1 2 3 4 5 6 7 8 9]


In [67]:
array3 = array1[0:3]
print(array3)

array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)
print(type(array6))

[1 2 3]
[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [69]:
array1d = np.arange(start=1,stop=10)
array2d = array1d.reshape(3,3)

print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [91]:
print(array2d[0:2, 0:2],'\n')

print(array2d[1:3,0:3],'\n')

print(array2d[1:3,:],'\n')

print(array2d[:,:], '\n')

print(array2d[:2, 1:], '\n')

print(array2d[:2,0], '\n')

[[1 2]
 [4 5]] 

[[4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]] 

[1 4] 



### 2.3 팬시 인덱싱 (fancy indexing)

In [94]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

print(array2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [97]:
array3 = array2d[[0,1], 2]
print(array3.tolist())

array4 = array2d[[0,2], 0:2]
print(array4.tolist())

array5 = array2d[[0,1]]
print(array5.tolist())

[3, 6]
[[1, 2], [7, 8]]
[[1, 2, 3], [4, 5, 6]]


### 2.4 불린 인덱싱 (boolean indexing)

In [101]:
array1d= np.arange(start=1, stop=10)

print(array1d)
print(array1d > 5)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]


In [102]:
var1 = array1d > 5

print(var1)
print(type(var1))

[False False False False False  True  True  True  True]
<class 'numpy.ndarray'>


In [103]:
# [ ] 안에 불린 인덱싱을 적용

array3 = array1d[array1d > 5]
print(array3)

[6 7 8 9]


In [107]:
# 불린 인덱싱으로 필터링

boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]

print(array3)

[6 7 8 9]


In [110]:
# 일반 인덱싱으로 필터링

nomal_indexes = np.array([5,6,7,8])
array4 = array1d[nomal_indexes]

print(array4)

[6 7 8 9]


In [112]:
array1d = np.arange(start=1, stop=10)
target = []

for i in range(0,9):
    if array1d[i] > 5:
        target.append(array1d[i])
        
array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [115]:
print(array1d[array1 > 5])

[6 7 8 9]


## 3. 행렬의 정렬

### 3.1 sort()

In [122]:
# 원본 행렬

org_array = np.array([3,1,9,5])
print(org_array)

[3 1 9 5]


In [123]:
# np.sort로 정렬

sort_array1 = np.sort(org_array)

print(sort_array1)    # 반환된 정렬 행렬
print(org_array)      # 호출 후 원본 행렬

[1 3 5 9]
[3 1 9 5]


In [119]:
# ndarray.sort로 정렬

sort_array2 = org_array.sort()

print(sort_array2)    # 반환된 행렬
print(org_array)      # 호출 후 원본 행렬

None
[1 3 5 9]


In [127]:
sort_array1_desc = np.sort(org_array)[::-1]    # 내림차순 정렬
print(sort_array1_desc)

[9 5 3 1]


In [130]:
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis=0)    # 로우방향 정렬
print(sort_array2d_axis0, '\n')

sort_array2d_axis1 = np.sort(array2d, axis=1)    # 컬럼방향 정렬
print(sort_array2d_axis1)

[[ 7  1]
 [ 8 12]] 

[[ 8 12]
 [ 1  7]]


### 3.2 argsort()

In [136]:
# 원본 행렬

org_array = np.array([3, 1, 9, 5])
print(org_array)

[3 1 9 5]


In [138]:
# sort 정렬

print(np.sort(org_array))

[1 3 5 9]


In [139]:
# argsort 정렬

sort_indices = np.argsort(org_array)

print(sort_indices)    # 행렬 정렬 시 원본 행렬의 인덱스
print(type(sort_indices))

[1 0 3 2]
<class 'numpy.ndarray'>


In [141]:
# sort 정렬

print(np.sort(org_array[::-1]))

[1 3 5 9]


In [142]:
sort_indices_desc = np.argsort(org_array)[::-1]
print(sort_indices_desc)

[2 3 0 1]


Key-Value 형태의 데이터를 ndarray로 만들고 argsort()를 이용하여 key 값 정렬<br>
> 점수: John=78, Mike=95, Sarah=84, Kate=98, Samuel=88

In [3]:
name_array = np.array(['John','Mike','Sarah','Kate','Samuel'])
score_array = np.array([78,95,84,98,88])

In [10]:
# score_array의 정렬된 값에 해당하는 원본 행렬 위치 인덱스 반환
sort_indices = np.argsort(score_array) 
print(sort_array)

[0 2 4 1 3]


In [11]:
# 이를 이용하여 name_array에서 name값 추출
name_array_sort = name_array[sort_indices]
score_array_sort = score_array[sort_indices]

print(name_array_sort)
print(score_array_sort)

['John' 'Sarah' 'Samuel' 'Mike' 'Kate']
[78 84 88 95 98]


## 4. 선형대수 연산

### 4.1 행렬 내적

In [145]:
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print(dot_product)

[[ 58  64]
 [139 154]]


### 4.2 전치 행렬

In [146]:
A = np.array([[1,2],
             [3,4]])

transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
